language: cpp
addons:
  apt:
    sources:
        # Clang 5.0
        - llvm-toolchain-trusty-5.0
        # Newer GCC
        - ubuntu-toolchain-r-test
    packages:
        - cmake
        - cmake-data
        - liblapack-dev
        - libhdf5-serial-dev
        - gcc-7
        - g++-7
        - clang-5.0
env:
    global:
    # should be limited to 4 on travis
    - OMP_NUM_THREADS=4
    # make cmake verbose
    - VERBOSE=1
    matrix:
    # test three different compilers
    - OUR_CXX='clang++-5.0' OUR_CC='clang-5.0' BUILD_TYPE='release'
    - OUR_CXX='g++-7' OUR_CC='gcc-7' BUILD_TYPE='release'
install:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=$OUR_CC -DCMAKE_CXX_COMPILER=$OUR_CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    - make
script:
    # we put a timeout of 90 minutes
    - travis_wait 90 make test ARGS="-V"
